### ISSUE TITLE
Coding error detected

### ISSUE THREAD

**Issue by mhussein67** [LafColITS/moodle-tool_deletecourses#15] opened 2021-06-25 21:00 UTC
Hi
The adhoc job produces the below error, please help

Adhoc task failed: tool_deletecourses\task\delete_courses_task,Coding error detected, it must be fixed by a programmer: A lock was created but not released at:
/var/www/html/myportal.acm.edu.kw/admin/tool/deletecourses/classes/task/delete_courses_task.php on line 108

 Code should look like:

 $factory = \core\lock\lock_config::get_lock_factory('type');
 $lock = $factory->get_lock(Resource id #1272);
 $lock->release();  // Locks must ALWAYS be released like this.

**Comment by mackensen** [comment] 2021-07-06 17:18
@mhussein67 is it possible for you to enable debugging and re-run? The lock failure means something went wrong, but it's a symptom and not the cause.

**Comment by bfriesenvcc** [comment] 2023-07-06 18:02
We are getting similar for plugin v3.9.0 (2022041200) for Moodle 3.9.17. Everything worked great and then it came to a grinding halt.

Execute adhoc task: tool_deletecourses\task\delete_courses_task
... started 10:08:04. Current memory use 64.7MB.
... used 696 dbqueries
... used 0.33661603927612 seconds
Adhoc task failed: tool_deletecourses\task\delete_courses_task,Coding error detected, it must be fixed by a programmer: A lock was created but not released at:
/data/shares/myschool/moodle-3.9.17/admin/tool/deletecourses/classes/task/delete_courses_task.php on line 109

Code should look like:

 $factory = \core\lock\lock_config::get_lock_factory('type');
 $lock = $factory->get_lock(a556ff9e35d7dfa4e9a71c372e887bdf196460e2);
 $lock->release();  // Locks must ALWAYS be released like this.

**Comment by mackensen** [comment] 2023-07-06 18:38
I'm going to close this in favor of #18, which has more traffic, since it's probably the same underlying issue.

**Closed as completed by mackensen** 2023-07-06 18:38 UTC
